site_name: LightGraphsExtras.jl
site_author: Seth Bromberger
repo_url: https://github.com/JuliaGraphs/LightGraphsExtras.jl/
theme: readthedocs
pages:
  - 'Getting Started': 'index.md'
  - 'Matching': 'matching.md'
  - 'Spectral': 'spectral.md'
  - 'Network Interdiction': 'interdiction.md'
docs_dir: 'doc'
markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_css:
  - LightGraphsExtras.css
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
